// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { CheckCircle, Clock, Smile } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutFeaturesSplit
          tag="About Us"
          title="Convenient, Clean, & Reliable Local Laundry"
          description="We believe doing laundry should be the simplest part of your day. Located in the heart of Ware, our laundromat is designed to be family-friendly, well-lit, and clean, providing you with a comfortable environment while you take care of your laundry needs."
          items={[
            {
              icon: CheckCircle,
              title: "Modern Machines",
              description: "High-efficiency washers and dryers for all load sizes.",
            },
            {
              icon: Clock,
              title: "Flexible Hours",
              description: "Open early and late to fit your busy schedule.",
            },
            {
              icon: Smile,
              title: "Family Friendly",
              description: "Safe, clean, and welcoming environment for all.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/medium-shot-man-garage-sale_23-2150574532.jpg?_wi=1"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
