// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Visit Us"
          text="Located in the heart of Ware. Come visit us today for a clean, easy, and stress-free laundry experience."
          primaryButton={{
            text: "Call Now: 413-555-0123",
            href: "tel:4135550123",
          }}
          secondaryButton={{
            text: "Get Directions",
            href: "https://maps.google.com/?q=Laundromat+Ware+MA",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
