// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Common Questions"
          title="We're Here to Help"
          description="Have questions about your visit? Find answers below."
          categories={[
            {
              name: "General",
              items: [
                {
                  question: "Where are you located?",
                  answer: "We are centrally located in downtown Ware, MA.",
                },
                {
                  question: "Are you open on weekends?",
                  answer: "Yes, we are open seven days a week.",
                },
              ],
            },
            {
              name: "Services",
              items: [
                {
                  question: "Do you offer wash-dry-fold?",
                  answer: "Please inquire at our service desk regarding full service options.",
                },
                {
                  question: "Do you have change machines?",
                  answer: "Yes, change machines are available onsite.",
                },
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
