// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardBrand from '@/components/sections/hero/HeroBillboardBrand';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardBrand
          brand="Coin Laundry"
          description="Clean Clothes. Easy Laundry. Right Here in Ware, MA. Your friendly local spot for quick, reliable wash-and-dry services."
          primaryButton={{
            text: "Get Directions",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Call Us Now",
            href: "tel:4135550123",
          }}
          imageSrc="https://storage.googleapis.com/webild/users/user_3HyWygIw3kCD5enT6ADPad4uVIu/uploaded-1786844408338-2m3c20wj.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
