// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="Why Choose Us"
          title="Quality at Every Turn"
          description="Dedicated to maintaining the highest standards for our community."
          metrics={[
            {
              value: "24/7",
              description: "Reliable Service Available",
            },
            {
              value: "15+",
              description: "Large Load Capacity Washers",
            },
            {
              value: "100%",
              description: "Customer Satisfaction Goal",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
