// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesComparison from '@/components/sections/features/FeaturesComparison';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesComparison
          tag="Our Services"
          title="Comprehensive Laundry Solutions"
          description="Whether it's a quick wash or a full weekend's load, we've got you covered."
          negativeItems={[
            "High wait times",
            "Old, dirty machines",
            "Uncomfortable waiting areas",
          ]}
          positiveItems={[
            "Clean, well-maintained facility",
            "Large-capacity machines available",
            "Safe, brightly lit atmosphere",
            "Quick, efficient cycles",
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
