// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialRatingCards from '@/components/sections/testimonial/TestimonialRatingCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialRatingCards
          tag="What Our Neighbors Say"
          title="Trusted by Local Families"
          description="See why our customers keep coming back to Coin Laundry."
          testimonials={[
            {
              name: "Alice T.",
              role: "Ware Resident",
              quote: "The cleanest laundromat in Ware! I love the large capacity machines.",
              rating: 5,
              imageSrc: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400",
            },
            {
              name: "Bob M.",
              role: "Local Business Owner",
              quote: "Reliable and always open when I need it. Great customer service.",
              rating: 5,
              imageSrc: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
            },
            {
              name: "Cindy L.",
              role: "Busy Mom",
              quote: "Safe and bright environment for my family. Highly recommend.",
              rating: 5,
              imageSrc: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400",
            },
            {
              name: "David W.",
              role: "Ware Resident",
              quote: "Best laundromat near me. Always well maintained.",
              rating: 5,
              imageSrc: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400",
            },
            {
              name: "Emma H.",
              role: "Student",
              quote: "Affordable and very user-friendly equipment.",
              rating: 5,
              imageSrc: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=400",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
